-- 41. NVL Functions Examples
SELECT FIRST_NAME, NVL(COMMISSION_PCT, 0) AS COMM
FROM EMPLOYEES;

SELECT FIRST_NAME, NVL2(COMMISSION_PCT, 'Has Commission', 'No Commission') AS COMM_STATUS
FROM EMPLOYEES;

SELECT FIRST_NAME, NULLIF(SALARY, 10000) AS SALARY_NULLIF
FROM EMPLOYEES;

SELECT FIRST_NAME, COALESCE(COMMISSION_PCT, 0.05, 0.1) AS COALESCE_EXAMPLE
FROM EMPLOYEES;
