-- 45. Group Functions Overview:
-- AVG, COUNT, MAX, MIN, STDDEV, SUM, VARIANCE

-- 46. Basic aggregate functions
SELECT AVG(SALARY), MAX(SALARY),
       MIN(SALARY), SUM(SALARY)
FROM EMPLOYEES

-- 47. Aggregate functions with condition
SELECT AVG(SALARY), MAX(SALARY),
       MIN(SALARY), SUM(SALARY)
FROM EMPLOYEES
WHERE JOB_ID LIKE '%REP%'

-- 48. Count all rows
SELECT COUNT(*)
FROM EMPLOYEES

-- 49. Count rows with condition
SELECT COUNT(*) 
FROM EMPLOYEES
WHERE DEPARTMENT_ID = 10

-- 50. Count distinct departments
SELECT COUNT(DISTINCT DEPARTMENT_ID)
FROM EMPLOYEES

-- 51. Count distinct commission percentages
SELECT COUNT(DISTINCT COMMISSION_PCT)
FROM EMPLOYEES

-- 52. Count non-null commission percentages
SELECT COUNT(COMMISSION_PCT)
FROM EMPLOYEES

-- 53. Group functions ignore nulls
SELECT SUM(COMMISSION_PCT)
FROM EMPLOYEES

-- 54. Include nulls using NVL
SELECT SUM(NVL(COMMISSION_PCT, 0))
FROM EMPLOYEES

-- 55. Group salary by department
SELECT DEPARTMENT_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
ORDER BY DEPARTMENT_ID

-- 56. Group salary by department and job
SELECT DEPARTMENT_ID, JOB_ID, SUM(SALARY)
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID, JOB_ID
ORDER BY DEPARTMENT_ID, JOB_ID

-- 57. Missing GROUP BY clause (invalid)
SELECT DEPARTMENT_ID, COUNT(FIRST_NAME)
FROM EMPLOYEES

-- 58. Fix by grouping by department
SELECT DEPARTMENT_ID, COUNT(FIRST_NAME)
FROM EMPLOYEES 
GROUP BY DEPARTMENT_ID

-- 59. Invalid use of WHERE with group function
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
WHERE AVG(SALARY) > 8000
GROUP BY DEPARTMENT_ID

-- 60. Correct use with HAVING
SELECT DEPARTMENT_ID, AVG(SALARY)
FROM EMPLOYEES
HAVING AVG(SALARY) > 8000 
GROUP BY DEPARTMENT_ID

-- 61. Invalid: MAX(AVG()) with department_id in SELECT
SELECT DEPARTMENT_ID, MAX(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID

-- 62. Correct aggregation using MAX of averages
SELECT MAX(AVG(SALARY))
FROM EMPLOYEES
GROUP BY DEPARTMENT_ID
