-- 63. Natural join with DEPARTMENTS
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, FIRST_NAME
FROM EMPLOYEES
NATURAL JOIN DEPARTMENTS
ORDER BY DEPARTMENT_ID

-- 64. Join using specific column
SELECT DEPARTMENT_ID, DEPARTMENT_NAME, FIRST_NAME
FROM EMPLOYEES JOIN DEPARTMENTS
USING (DEPARTMENT_ID)

-- 65. Join with aliases using USING
SELECT DEPARTMENT_ID, D.LOCATION_ID, E.FIRST_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
USING (DEPARTMENT_ID)

-- 66. Join using ON condition
SELECT D.DEPARTMENT_ID, D.LOCATION_ID, E.FIRST_NAME
FROM EMPLOYEES E JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)

-- 67. Self join to get manager names
SELECT E.LAST_NAME AS EmployeeName, M.LAST_NAME AS ManagerName
FROM EMPLOYEES E JOIN EMPLOYEES M
ON (E.EMPLOYEE_ID = M.MANAGER_ID)

-- 68. Same self join with condition on manager_id
SELECT E.LAST_NAME AS EmployeeName, M.LAST_NAME AS ManagerName
FROM EMPLOYEES E JOIN EMPLOYEES M
ON (E.EMPLOYEE_ID = M.MANAGER_ID)
AND M.MANAGER_ID = 100

-- 69. Join across 3 tables to get city and department
SELECT E.LAST_NAME AS EmployeeName, M.LAST_NAME AS ManagerName, D.DEPARTMENT_NAME, L.CITY
FROM EMPLOYEES E JOIN EMPLOYEES M
ON (E.EMPLOYEE_ID = M.MANAGER_ID)
            JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
            JOIN LOCATIONS L
ON (D.LOCATION_ID = L.LOCATION_ID)

-- 70. Join employees with job grades based on salary range
SELECT E.LAST_NAME, E.SALARY, J.GRADE_LEVEL
FROM EMPLOYEES E JOIN JOB_GRADES J
ON E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL

-- 71. Left outer join
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E LEFT OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)

-- 72. Right outer join
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E RIGHT OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)

-- 73. Full outer join
SELECT E.LAST_NAME, D.DEPARTMENT_NAME
FROM EMPLOYEES E FULL OUTER JOIN DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)

-- 74. CROSS JOIN example (Cartesian product)
SELECT FIRST_NAME, DEPARTMENT_NAME
FROM EMPLOYEES CROSS JOIN DEPARTMENTS
