-- 75. Practice 5 Overview:
-- Examples:
-- 1. SELECT E.FIRST_NAME, D.DEPARTMENT_NAME 
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID;

-- 2. SELECT E.FIRST_NAME, M.FIRST_NAME AS MANAGER
FROM EMPLOYEES E JOIN EMPLOYEES M 
ON E.MANAGER_ID = M.EMPLOYEE_ID;

-- 3. SELECT E.FIRST_NAME, L.CITY 
FROM EMPLOYEES E JOIN DEPARTMENTS D 
ON E.DEPARTMENT_ID = D.DEPARTMENT_ID 
JOIN LOCATIONS L 
ON D.LOCATION_ID = L.LOCATION_ID;

-- 4. SELECT E.FIRST_NAME, J.GRADE_LEVEL 
FROM EMPLOYEES E JOIN JOB_GRADES J 
ON E.SALARY BETWEEN J.LOWEST_SAL AND J.HIGHEST_SAL;
